
spring:
  config.activate.on-profile: default
  web.resources.static-locations: "file:./app"  
  datasource:
    url: jdbc:sqlite:/Users/murong/Downloads/cap4test/z871servce/z871servce.db
    jdbc.driver: org.sqlite.JDBC  
cds:
  datasource.auto-config.enabled: true
  odata-v4.endpoint.path: "/api" 
  security.mock.users:
    - name: admin
      password: admin
      roles:
      - admin

